### ISSUE TITLE
goagentx开关快捷键

### ISSUE THREAD

**Issue by ghost** [loggerhead/Easy-Karabiner#4]
你好，我想设置goagentx开关的快捷键，不知道有设么好方法。

**Comment by loggerhead** [comment]
没用过 goagentx，不清楚怎么开关它。不过我猜想可能是下面这两种情况中的一种：
- 点击 menu 中的 item：
  
  ![image](https://cloud.githubusercontent.com/assets/5056390/15884393/ad58ec98-2d82-11e6-9075-58c897f4ca30.png)
- 点击 window 中的 button：
  
  ![image](https://cloud.githubusercontent.com/assets/5056390/15884412/d37fac54-2d82-11e6-95bd-1c09e532f500.png)

有几种可能的方法，你可以试试：
1. 使用 [Keyboard Maestro](https://www.keyboardmaestro.com/main/)，它可以模拟按键、鼠标点击等一些事情；
2. 编写 AppleScript 脚本，通过 Karabiner 调用它进行开关（见 [samples/myconfig.py](https://github.com/loggerhead/Easy-Karabiner/blob/master/samples/myconfig.py) 中 `mouse_left` 那一行）。AppleScript 能够操纵任何调用了系统 API 生成的 GUI 界面，所以模拟点击 button 这种事情不在话下；
3. 如果 goagentx 或 goagent 有命令行的开关方式，你可以通过编写一个 Shell 脚本，再通过 Karabiner 调用（见 [KeyCombo 的用法](https://github.com/loggerhead/Easy-Karabiner#keycombo)）。

**Comment by ghost** [comment]
非常感谢！！
